# This YAML file contains busybox & csi arstor driver objects,
# which are necessary to run busybox with csi arstor driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-arstorplugin
provisioner: arstor.csi.huayun.io
parameters:
  fsType: xfs


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-arstorplugin
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-arstorplugin

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  dnsPolicy: ClusterFirst
  containers:
  - name: busybox
    image: busybox:1.28.4
    securityContext:
      runAsUser: 0
    command: ["sh","-c","ls -l /dev/xvda ; tail -f /dev/null "]
    imagePullPolicy: IfNotPresent
    volumeDevices:
      - devicePath: /dev/xvda
        name: csi-data-arstorplugin
  restartPolicy: Always
  volumes:
  - name: csi-data-arstorplugin
    persistentVolumeClaim:
      claimName: csi-pvc-arstorplugin
      readOnly: false